### ISSUE TITLE
differance between orders wrt original direction

### ISSUE THREAD

**Issue by pannet1** [uberdeveloper/omspy#16]
##feature request##
you can differentiate between buy trade and sell trade like below

'''buy trade'''
buy / sell
'''sell trade'''
short / cover

**Comment by uberdeveloper** [comment]
An order is an independent entity and closely resembles an order at the exchange with extra information. Covering an order requires broker positions to determine the side.

To cover your orders manually, use the following broker methods

- `close_all_positions`
- `cover_orders`

To automatically cover orders, use orders in the `stop` module
To extend custom functionality, sub class `CompoundOrder`
