### ISSUE TITLE
finvasia.yaml file not found anywhere in repo

### ISSUE THREAD

**Issue by soumyarai2050** [uberdeveloper/omspy#28]
File: tests/brokers/test_finvasia.py

`@pytest.fixture`
`def mod():`
`    with open("omspy/brokers/finvasia.yaml") as f:`
`        return yaml.safe_load(f)`

file finvasia.yaml is not found anywhere in repo

**Comment by uberdeveloper** [comment]
You could find it under 
`omspy/brokers/finvasia.yaml`
